---

- name: Create kubernetes roles for node.
  vars:
    cert_types:
      - "kube_etcd"
      - "kube_etcd_peer"
      - "kube_etcd_healthcheck_client"
      - "kube_apiserver_etcd_client"
      - "kube_apiserver"
      - "kube_apiserver_kubelet_client"
      - "front_proxy_client"
      - "kubelet"
    certs_path:
      kube_etcd: "etcd"
      kube_etcd_peer: "etcd"
      kube_etcd_healthcheck_client: "etcd"
      kube_apiserver_etcd_client: "etcd"
      kube_apiserver: "kubernetes"
      kube_apiserver_kubelet_client: "kubernetes"
      front_proxy_client: "kubernetes_front_proxy"
      kubelet: "kubernetes"
    certs:
      kube_etcd:
        key_usage:
          - "ServerAuth"
          - "ClientAuth"
        domains:
          - "kube-etcd"
          - "{{ cert_hostname }}"
          - "localhost"
        localhost: true
        ip_sans: true
        organization: ""
      kube_etcd_peer:
        key_usage:
          - "ServerAuth"
          - "ClientAuth"
        domains:
          - "kube-etcd-peer"
          - "{{ cert_hostname }}"
          - "localhost"
        localhost: true
        ip_sans: true
        organization: ""
      kube_etcd_healthcheck_client:
        key_usage:
          - "ClientAuth"
        domains: [ "kube-etcd-healthcheck-client" ]
        localhost: false
        ip_sans: false
        organization: ""
      kube_apiserver_etcd_client:
        key_usage:
          - "ClientAuth"
        domains: [ "kube-apiserver-etcd-client" ]
        localhost: false
        ip_sans: false
        organization: ""
      kube_apiserver:
        key_usage:
          - "ServerAuth"
        domains:
          - "kube-apiserver"
          - "{{ cert_hostname }}"
          - "kubernetes"
          - "kubernetes.default"
          - "kubernetes.default.svc"
          - "kubernetes.default.svc.cluster"
          - "kubernetes.default.svc.cluster.local"
        localhost: false
        ip_sans: true
        organization: ""
      kube_apiserver_kubelet_client:
        key_usage:
          - "ClientAuth"
        domains: [ "kube-apiserver-kubelet-client" ]
        localhost: false
        ip_sans: false
        organization: "system:masters"
      front_proxy_client:
        key_usage:
          - "ClientAuth"
        domains: [ "front-proxy-client" ]
        localhost: false
        ip_sans: false
        organization: ""
      kubelet:
        key_usage:
          - "ClientAuth"
        domains: [ "system:nodes:{{ cert_hostname }}" ]
        localhost: false
        ip_sans: false
        organization: "system:nodes"
  block:
    - name: Loop over roles.
      include_tasks: "create.yml"
      loop: "{{ cert_types }}"
      loop_control:
        loop_var: cert_type