---

- name: Force handlers.
  debug:
    msg: "Force handlers !"
  tags: force-handlers
  changed_when: true
  notify: force-handlers
- name: Disable swap.
  lineinfile:
    path: "/etc/fstab"
    regexp: "^([^#].*swap.*)$"
    line: "# \\1"
    state: present
    backrefs: true
  notify: disable-swap
- name: Copy containerd modules conf.
  copy:
    src: "containerd-modules.conf"
    dest: "/etc/modules-load.d/containerd.conf"
  notify: enable-modules
- name: Copy ip forwarding config.
  copy:
    src: "ipforward.conf"
    dest: "/etc/sysctl.d/99-kubernetes-k8s.conf"
  notify: reload-system
- name: Add k8s apt key.
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    state: present
- name: Add k8s apt repository.
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb /"
    state: present
- name: Update apt.
  apt:
    update_cache: true
- name: Install containerd.
  apt:
    name: "containerd={{ containerd_version }}"
    state: present
- name: Hold containerd.
  dpkg_selections:
    name: containerd
    selection: hold
- name: Copy containerd config.
  copy:
    src: "containerd.toml"
    dest: "/etc/containerd/config.toml"
  notify: restart-containerd
- name: Enable containerd.
  systemd_service:
    name: containerd
    enabled: true
- name: Install k8s.
  apt:
    pkg:
      - "kubelet={{ k8s_package_version }}"
      - "kubeadm={{ k8s_package_version }}"
      - "kubectl={{ k8s_package_version }}"
    state: present
- name: Hold kubelet.
  dpkg_selections:
    name: kubelet
    selection: hold
- name: Hold kubeadm.
  dpkg_selections:
    name: kubeadm
    selection: hold
- name: Hold kubectl.
  dpkg_selections:
    name: kubectl
    selection: hold