---

- name: Create kubernetes roles for node.
  vars:
    cert_types:
      - "controller_manager"
      - "scheduler"
    certs_path:
      controller_manager: "kubernetes"
      scheduler: "kubernetes"
    certs:
      controller_manager:
        key_usage:
          - "ExtKeyUsageClientAuth"
        domains: [ "system:kube-controller-manager" ]
        localhost: false
        ip_sans: false
        organization: ""
      scheduler:
        key_usage:
          - "ExtKeyUsageClientAuth"
        domains: [ "system:kube-scheduler" ]
        localhost: false
        ip_sans: false
        organization: ""
  block:
    - name: Loop over roles.
      include_tasks: "block.yml"
      loop: "{{ cert_types }}"
      loop_control:
        loop_var: cert_type