---

- name: Check if root-ca exists.
  community.hashi_vault.vault_read:
    path: "{{ engine_path }}/issuer/{{ root_ca_ref }}"
  register: issuer_ref
  ignore_errors: true
  changed_when: false
- name: Write root-ca if not exists.
  community.hashi_vault.vault_write:
    path: "{{ engine_path }}/root/generate/internal"
    data:
      issuer_name: "{{ root_ca_ref }}"
      key_name: "key.{{ root_ca_ref }}"
      common_name: "{{ root_common }}"
      ttl: "{{ ttl }}"
      key_bits: "{{ key_bits }}"
      max_path_length: "{{ max_path_length }}"
      ou: "{{ ou }}"
      organization: "{{ organization }}"
      country: "{{ country }}"
      locality: "{{ locality }}"
      province: "{{ province }}"
      street_address: "{{ street_address }}"
      postal_code: "{{ postal_code }}"
  when: issuer_ref.data is not defined
- name: Set issuer data.
  community.hashi_vault.vault_write:
    path: "{{ engine_path }}/issuer/{{ root_ca_ref }}"
    data:
      leaf_not_after_behaviour: "truncate"
      issuing_certificates:
        - "{{ vault_addr }}/v1/{{ engine_path }}/ca"
      crl_distribution_points:
        - "{{ vault_addr }}/v1/{{ engine_path }}/crl"
      ocsp_servers:
        - "{{ vault_addr }}/v1/{{ engine_path }}/ocsp"